
from tests.parser.test_parse_docstring_author import TestParseDocstring_Author
from tests.parser.test_parse_docstring_copyright import TestParseDocstring_Copyright
from tests.parser.test_parse_docstring_deprecated import TestParseDocstring_Deprecated
from tests.parser.test_parse_docstring_example import TestParseDocstring_Examples
from tests.parser.test_parse_docstring_global import TestParseDocstring_Global
from tests.parser.test_parse_docstring_ignore import TestParseDocstring_Ignore
from tests.parser.test_parse_docstring_license import TestParseDocstring_License
from tests.parser.test_parse_docstring_memberof import TestParseDocstring_Memberof
from tests.parser.test_parse_docstring_namespace import TestParseDocstring_Namespace
from tests.parser.test_parse_docstring_param import TestParseDocstring_Param
from tests.parser.test_parse_docstring_private import TestParseDocstring_Private
from tests.parser.test_parse_docstring_public import TestParseDocstring_Public
from tests.parser.test_parse_docstring_returns import TestParseDocstring_Returns
from tests.parser.test_parse_docstring_throws import TestParseDocstring_Throws
from tests.parser.test_parse_docstring_since import TestParseDocstring_Since
from tests.parser.test_parse_docstring_todo import TestParseDocstring_Todo
from tests.parser.test_parse_docstring_version import TestParseDocstring_Version

from tests.parser.test_parse_docstring import TestParseDocstring

from tests.parser.test_parse_function import TestParseFunction

from tests.parser.test_parse_class import TestParseClass

from tests.parser.test_parse_module import TestParseModule
